name: Windows Server 2019

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: Seu codigo remote
        required: true
      pin:
        description: sua senha de 6 digitos
        required: true
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Iniciando settings
        run: |
          ./windows_config/setting.ps1
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
      - name: Windows server pronto!
        run: sleep 86400
